services:

  apprendre-poesie:
    image: caddy:latest
    ports:
      - '${PORT}:80'
    restart: always
    volumes:
      - './Caddyfile:/etc/Caddyfile'
      - './src/:/usr/share/caddy/'
    healthcheck:
      test: ["CMD", "curl", "-f", ${SERVICE_URL_APPRENDRE_POESIE}]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s

